language: node_js
node_js:
  - 9
before_script:
  - npm install -g gatsby-cli
  - git config --global github-oauth.github.com "$githubsecuritytoken"
cache:
  directories:
    - "node_modules"

after_success: npm run deploy
# safelist
branches:
  only:
  - master

