language: node_js
node_js:
  - 9
before_script:
  - npm install -g gatsby-cli
cache:
  directories:
    - "node_modules"

after_success:
  - git config --global github-oauth.github.com "$githubsecuritytoken"
  - npm run deploy

# safelist
branches:
  only:
  - master

